greatscottgadgets/hackrf

- host/libhackrf/src/hackrf.h
So that I don't have to keep googling for this every time I forget which
knob is which.
From http://nine.pairlist.net/pipermail/hackrf-dev/2014-March/000276.html
> quick reminder of gain control mappings

- firmware/common/hackrf_core.h
- firmware/hackrf_usb/hackrf_usb.c
- host/hackrf-tools/src/hackrf_transfer.c
- host/libhackrf/src/hackrf.c
- host/libhackrf/src/hackrf.h
Using the patch from @supersat
> Fix issue #113 - CPLD update fails on Windows

- host/README.md
- host/libhackrf/CMakeLists.txt
Not sure if lib vs. libdata fix is correct, please verify:
`set(libpkgdata "lib"${LIB_SUFFIX})`
When do you plan to make a next release? It would be nice to catch up and create a FreeBSD port for a new release :-)
> Added FreeBSD support for HOST part.

- host/hackrf-tools/src/hackrf_transfer.c
- host/libhackrf/src/hackrf.c
> Explain which gain setting was unacceptable

- host/hackrf-tools/src/hackrf_transfer.c
Add a "-R" parameter, when TX input file gets to end, using "-R" parameter can easily do repeat TX, which is useful for testing.
> Add file repeat TX mode [-R].

- .gitattributes
GitHub currently thinks the repo is 73% Eagle
> Fix KiCad files being detected as Eagle files

- host/hackrf-tools/src/hackrf_transfer.c
addressing the comments in #189
> allow user to specify frequencies in scientific notation

- host/hackrf-tools/src/hackrf_si5351c.c
I had to do some refactoring and nested ifs to get this working. I tested the outcomes, apart from the serial number call - my hackrfs have old firmware so the serial number code doesn't work with them.
> Added flags + code to hackrf_si5351c program, to open device by index or serial number

- appveyor.yml
- host/CMakeLists.txt
- host/README.md
- host/hackrf-tools/CMakeLists.txt
- host/hackrf-tools/src/CMakeLists.txt
- host/libhackrf/CMakeLists.txt
It's probably best to squash this in to one commit when you merge it.
> Appveyor config for building hackrf_sweep

- host/hackrf-tools/src/hackrf_operacake.c
For OperaCake, I should have specified that in the commit comment
> fixed ports to allow users to pass port name on board

- firmware/common/hackrf_core.c
- firmware/common/mixer.c
Miscellaneous stuff, but the last commit actually fixes TX.
> rad1o fixes

- firmware/common/hackrf_core.c
- firmware/common/si5351c.c
- firmware/common/si5351c.h
- firmware/hackrf_usb/hackrf_usb.c
- firmware/hackrf_usb/usb_api_register.c
- firmware/hackrf_usb/usb_api_register.h
- host/CMakeLists.txt
- host/hackrf-tools/src/CMakeLists.txt
- host/hackrf-tools/src/hackrf_clock.c
- host/libhackrf/src/hackrf.c
- host/libhackrf/src/hackrf.h
This tool allows us to show the configuration of the various clocks in the si5351 and turn on/off the one connected to CLKOUT.
> Clock util

- host/hackrf-tools/src/hackrf_operacake.c
Clean up port name parsing and error handling for both port setting and frequency range modes.
> Fix hackrf_operackae port name parsing

- host/hackrf-tools/src/hackrf_sweep.c
Adds the ability to sweep for a limited number of sweeps (more than 1-shot).
> Add limited sweep mode

- firmware/common/usb_standard_request.c
Linux issues a `GET_STATUS` request to validate that a USB device has correctly resumed after an idle suspend; but HackRF has thus far not implemented `GET_STATUS`. As a result, Linux assumes our USB devices are failing to resume, and winds up resetting them. Oops. ^-^
(This PR is meant to be consistent with the current state/style of the HackRF USB code -- I have a cleaner and more succinct version that I'll port over here after I merge it into GreatFET.)
> Fix communications failures on USB suspend. (#97)

- firmware/common/hackrf_core.c
- firmware/common/hackrf_core.h
- firmware/hackrf_usb/hackrf_usb.c
We don't hang out in low speed mode for long, it's not saving us power, and it's out of spec for PLL1
> Remove PLL1 low speed settings (it's out of spec)

- firmware/common/hackrf_ui.c
- firmware/common/hackrf_ui.h
- firmware/common/ui_portapack.c
- firmware/common/ui_rad1o.c
- firmware/hackrf_usb/CMakeLists.txt
- firmware/hackrf_usb/hackrf_usb.c
- firmware/hackrf_usb/usb_api_ui.c
- firmware/hackrf_usb/usb_api_ui.h
- firmware/hackrf_usb/usb_descriptor.c
- host/hackrf-tools/src/hackrf_debug.c
- host/libhackrf/src/hackrf.c
- host/libhackrf/src/hackrf.h
> Add option to disable HackRF UI

- firmware/hackrf_usb/hackrf_usb.c
- firmware/hackrf_usb/usb_api_transceiver.c
> Don't re-init bulk endpoints on every set_transceiver_mode call

- host/hackrf-tools/src/hackrf_sweep.c
> hackrf_sweep: switch main loop timing back to 1Hz

- Readme.md
> Update README with response times and documentation information

- docs/source/hackrf_projects_mentions.rst
- docs/source/index.rst
Update the page title, intro paragraph, and file name.
> update HackRF hacks page

- docs/source/hackrf_projects_mentions.rst
Remove dead links from projects and mentions page.
> update mentions page

- firmware/common/hackrf_core.c
this changes fixes #1003 by disabling cpld processing while changing the samplingrate
> fix stream glitch on rate change

- docs/source/opera_cake.rst
- host/hackrf-tools/src/hackrf_operacake.c
> update Opera Cake documentation

- firmware/common/operacake.c
- firmware/common/operacake.h
- firmware/hackrf_usb/usb_api_operacake.c
- host/hackrf-tools/src/hackrf_operacake.c
- host/libhackrf/src/hackrf.c
- host/libhackrf/src/hackrf.h
This fixes several bugs I found while working on Opera Cake documentation. The most significant one was that frequency mode had been completely broken by a change that I suggested. :smile:
> Fix Opera Cake bugs

- firmware/common/si5351c.c
fixes https://github.com/greatscottgadgets/hackrf/issues/1013
> keep clkout state over general clock reconfiguration

- host/libhackrf/src/hackrf.c
Sorry, I messed up while rebasing, so it closed the previous PR.
This one only contains the commit we talked about in https://github.com/greatscottgadgets/hackrf/pull/1057
>  proposal to fix regression in 4c9fcf86651232c2104b57510a0ac86cf86123e4 #1057 

- docs/source/hackrf_projects_mentions.rst
Static web page which uses WebUSB and HackRF to transimt a signal which
opens the Tesla charging port
> Add project mention for the Tesla charging port opener

- firmware/hackrf_usb/usb_api_sweep.c
This PR fixes a bug introduced by #982 (more precisely, by commit 9f79a16b261136d89d4baeff958168b7af8a71e6). The said change overlooked that in sweep mode the count of samples to be read for each frequency may be set to more than one block (tracked by the variable `dwell_blocks`, which became unused).
The diff is much-much simpler if whitespace changes are ignored.
> Bugfix in sweep mode when multiple blocks have to be read for each frequency

- ci-scripts/test-firmware-program.sh
> ci: update target device's changed port number

- docs/source/faq.rst
Hello!
I thought a bulleted list may make the information easier to read quickly.
What are your thoughts, suggestions, etc?
> Gain controls: bulleted list

- firmware/common/si5351c.c
CLKOUT now switches to the active clock source whenever the internal clocks change source. It previously did so only when (re)enabled.
> firmware: use consistent clock source

- firmware/README
It ain't much but it's honest work.
> fixed firmware manual build docs

- firmware/hackrf_usb/usb_api_transceiver.c
> Don't start baseband streaming until TX buffer is first filled.

- host/libhackrf/src/hackrf.c
It was possible in theory for a transfer to complete before `prepare_transfers` had finished initially submitting transfers, leading to various potential races or out-of-order data.
This PR prevents this by extending the scope of `transfer_lock` to more of the libusb transfer callback, and taking this lock during `prepare_transfers` until all initial submissions are complete.
After this change, it became possible to merge `all_finished_lock` with `transfer_lock`, which simplifies things significantly.
> Improve transfer locking

- docs/source/hackrf_one.rst
> Add picture of HackRF to documentation

- docs/source/troubleshooting.rst
> Docs: Update HackRF troubleshooting docs

- firmware/common/hackrf_core.c
- firmware/common/hackrf_core.h
- firmware/hackrf_usb/hackrf_usb.c
- firmware/hackrf_usb/usb_api_register.c
- firmware/hackrf_usb/usb_api_register.h
- firmware/hackrf_usb/usb_descriptor.c
- host/hackrf-tools/src/hackrf_debug.c
- host/libhackrf/CMakeLists.txt
- host/libhackrf/src/hackrf.c
- host/libhackrf/src/hackrf.h
and corresponding changes to libhackrf and firmware
> add --led option to hackrf_debug

- docs/source/faq.rst
Also added a comment on why is this value often quoted wrong
> Fix "14dB" RF amplification in FAQ

- host/libhackrf/src/hackrf.c
Did a search for allocations & all others were fine
> Fix memory waste in allocated_transfers

- host/hackrf-tools/src/hackrf_debug.c
> change the device long option to required in hackrf_debug

- Readme.md
> Readme.md: Fix typo

- docs/requirements.txt
Updates all RTD requirements to the latest versions, thereby fixing the docs build.
> Update readthedocs requirements to current versions.

- host/libhackrf/src/hackrf.h
Hi,
this commit fixes a few minor typos I noticed while reading the API documentation in hackrf.h
Best,
Simon
> hackrf.h: fix typos in documentation comments

- docs/source/list_of_hardware_revisions.rst
> Add spec statement to hardware revision docs

- firmware/hackrf_usb/sgpio_m0.s
This text had gotten a little out of sync with the code.
> Update SGPIO code documentation
