greatscottgadgets/hackrf

- host/CMakeLists.txt
- host/libhackrf/CMakeLists.txt
- host/misc/CMakeLists.txt
- host/misc/udev/53-hackrf.rules.in
- host/misc/udev/CMakeLists.txt
Allow udev group to be specified at configuration time, with intelligent defualts.
This should solve the problem for both sides of the plugdev/usb divide.
> Attempt to detect correct group for udev rule

- host/libhackrf/src/hackrf.c
Adds detach_kernel_drivers() and set_hackrf_configuration() functions.
detach_kernel_drivers() detaches drivers from all interfaces on the active config
set_hackrf_configuration() uses detach_kernel_drivers() to detach the drivers from the interface, then changes the config and then detaches any new drivers that may have attached themselves automatically after the config change.
> Fix GitHub issue #163 - Detach the kernel driver automatically

- firmware/common/w25q80bv.c
- firmware/common/w25q80bv.h
- firmware/hackrf_usb/hackrf_usb.c
- firmware/hackrf_usb/usb_api_spiflash.c
Addresses issue #213.
Commit 2022cc6 is optional, simplifies code by making the assumption that code is not executing from SPI flash after the ROM bootloader is done.
> hackrf_spiflash read fix

- host/libhackrf/53-hackrf.rules.in
- host/python/max2837_dump.py
- host/python/set_transceiver_mode.py
- udev rule should be lowercase (https://github.com/rad1o/f1rmware/pull/29)
- add entries for rad1o storage from https://github.com/rad1o/f1rmware/blob/master/smartflash/90-rad1o-flash.rules
- Rad1o -> rad1o
- hackrf.h was NOT adjusted to lowercase cc15
> rad1o USB idProduct cleanups

- host/libhackrf/src/hackrf.h
In ansi/c90 mode gcc warns about extra tokens at end of #endif directive [-Wendif-labels] when hackrf.h gets included. Changing the comment style gets rid off that.
> Comment style fixup to prevent warning in c90 complier mode

- host/hackrf-tools/src/hackrf_spiflash.c
Fixes #214 by using MAX_LENGTH as the default read length
> Default SPI flash read length to size of SPI flash

- firmware/dfu-util.cmake
- firmware/hackrf-common.cmake
Fixes issue #117 by allowing either dfu-util 0.7 or dfu-util 0.8 to be used.  If neither is installed, it prints a message that DFU files will not be built and does not build them.  This could be changed to an error if needed.
It's a little bit hacky.
> Support both commonly available versions of dfu-util (0.7/0.8)

- firmware/common/hackrf_core.c
CLK0 and CLK2 are clock outputs of the LPC43xx which are are activated by default.
During the rad1o development we identified them as sources of interference in the received spectrum (also on the HackRF).
I believe they are not used by anyone. We've disabled them in our rad1o fork.
> fix(hackrf-core): Disable unused clock outputs

- firmware/common/usb_standard_request.c
- firmware/common/usb_standard_request.h
- firmware/common/usb_type.h
- firmware/hackrf_usb/hackrf_usb.c
- firmware/hackrf_usb/usb_descriptor.c
- firmware/hackrf_usb/usb_descriptor.h
- firmware/hackrf_usb/usb_device.c
This adds the Windows Compatible ID that allows us to tell Windows hosts that we use the WinUSB driver.  It does not add the extended properties descriptor, as I was unsure of the benefit for HackRF, although I added the ability to set it if desired.
Host software such as SDR# will already have libusb, so this removes the step where users need to install libusb/zadig.
> Add WCID descriptors

- host/hackrf-tools/src/hackrf_transfer.c
When '-' is used for filename, write samples to stdout when receiving or
read samples from stdin when transmitting. This allows using
hackrf_transfer in shell pipes with tools like csdr.
User info messages are written to stderr.
> Add support for transmitting/receiving from stdin/stdout

- host/hackrf-tools/src/hackrf_transfer.c
I'm getting ready for new windows installers, just noticed this.
Real minor casting issue, here is the fix to get master compiling:
The compiler (MSVC 2013) didnt have the uint typedef,
switched to using uint32_t which is the type of sample_rate_hz.
> hackrf_transfer - cast with uint32_t

- host/hackrf-tools/src/hackrf_transfer.c
- host/libhackrf/src/hackrf.c
Both libhackrf and hackrf_transfer are using boolean flag named
"do_exit" which is not static. This is problematic because the flag is
used for different things. This patch fixes the problem by making the
flag static in both places.
Fixes issue #272
> Make the 'do_exit' flag static

- host/libhackrf/src/hackrf.c
- host/libhackrf/src/hackrf.h
The rad1o is the badge of the Chaos Communication Camp 2015 (CCCamp15).
The rad1o badge contains a full-featured SDR (software defined radio) half-duplex transceiver, operating in a frequency range of about 50 MHz - 4000 MHz, and is software compatible to the HackRF.
See https://rad1o.badge.events.ccc.de for more information.
> Add rad1o board id to libhackrf

- firmware/dfu.py
- firmware/hackrf-common.cmake
This removes a one line python command and puts it in to a script which supports both python 2 and 3.
> Replace python one liner with script to build dfu files

- .travis.yml
Add firmware to travis-ci build so that it covers all code changes.  This only builds the hackrf_usb firmware as it is the only one under active development.
We do nothing with the build artifacts, but in future we could offer binary firmware images in the way that the Portapack project does.
> Build firmware as part of Travis-ci build

- firmware/hackrf_usb/usb_descriptor.c
- host/hackrf-tools/src/hackrf_info.c
- host/hackrf-tools/src/hackrf_operacake.c
- host/hackrf-tools/src/hackrf_spiflash.c
- host/hackrf-tools/src/hackrf_sweep.c
- host/hackrf-tools/src/hackrf_transfer.c
- host/libhackrf/src/hackrf.c
- host/libhackrf/src/hackrf.h
Adding USB API version, based on USB descriptor bcdDevice.
Once a device has been found by libusb the calls to hackrf_usb_api_version_read() and USB_API_REQUIRED() should never fail.
Host tools can decide how to handle the error, for example the error is fatal for hackrf_operacake, hackrf_sweep, and hw_sync mode in hackrf_transfer.  The error is silently ignored in hackrf_info.
> Add USB API versioning

- firmware/common/hackrf_core.c
Most rad1o applications use more clocks than the HackRF. I've enabled the again for now and reintroduced the original clock output change for the rad1o.
> fix(rad1o): Restore old clock behaviour for now.

- firmware/common/operacake.c
- firmware/common/operacake.h
- firmware/common/tuning.c
- firmware/hackrf_usb/hackrf_usb.c
- firmware/hackrf_usb/usb_api_operacake.c
- firmware/hackrf_usb/usb_api_operacake.h
- firmware/hackrf_usb/usb_descriptor.c
- host/hackrf-tools/src/CMakeLists.txt
- host/hackrf-tools/src/hackrf_operacake.c
- host/libhackrf/src/hackrf.c
- host/libhackrf/src/hackrf.h
- HackRF switches antenna when tuning
- ports specified using hackrf_operacake cmdline tool
hackrf_operacake -f 2350:2800:0 -f 0:400:1 -f 400:700:2 -f 700:6000:3
> Opera glasses: allow user specified ranges for operacake ports

- host/hackrf-tools/src/hackrf_sweep.c
time_stamp.tv_usec was sent through modulo before time_stamp.tv_sec was updated
> Fixed a time_stamp bug in rx_callback()

- firmware/hackrf_usb/usb_descriptor.c
- host/hackrf-tools/src/hackrf_spiflash.c
I've added a check for the USB product string descriptor in the .bin file that `hackrf_spiflash` is writing.  It reads the board ID from the device and checks for the appropriate string in the binary firmware file.
I'm sure there are better / more reliable ways to detect this, but this seems to be relatively robust.
It reads the board ID, not the string from the board, so we can always change the board name in the future without breaking things.  If you're currently running a firmware that reports the incorrect board ID, then it probably isn't booting.
You canalwaysget around this check with `hackrf_spiflash -i` or DFUmode.
> Firmware compatibility check

- host/libhackrf/src/hackrf.c
Previously it incremented when the library was initialised, this worked
for GNU Radio flowgraphs, but broke elsewhere
> Open device counting: increment when opening a device

- appveyor.yml
- host/hackrf-tools/src/hackrf_clock.c
- host/hackrf-tools/src/hackrf_debug.c
- host/hackrf-tools/src/hackrf_operacake.c
- host/hackrf-tools/src/hackrf_sweep.c
- host/hackrf-tools/src/hackrf_transfer.c
- host/libhackrf/src/hackrf.c
This fixes 27 build warnings from MSVC on Windows.  Most of these were warnings about loss of precision, so I've added some explicit casts which silences the warnings and makes it more obvious what the code is doing.  I think this is win-win.
In some places we were seeing the same warning repeated, so I have added a couple of helper functions to parse frequencies from command line arguments.
> Remove Windows build warnings

- firmware/CMakeLists.txt
- firmware/blinky/CMakeLists.txt
- firmware/hackrf_usb/CMakeLists.txt
- host/CMakeLists.txt
By default, CMake assumes that the project is using both C and C++.  By
explicitly passing 'C' as argument of the project() macro, we tell CMake
that only C is used, which prevents CMake from erroring out if a C++
compiler doesn't exist.
> Don't require a C++ compiler

- .travis.yml
This PR moves includes a couple of travis related changes
- Updates xcode to xcode9.2
- Fix python pip TLSv1 deprecation that breaks the old brewed python pip
- Upgrades brewed libusb
- Removes included oclint because of conflicts 
This PR was intents to close issue #438
> Travis OS X builds don't work with modern Xcode #438

- .travis.yml
> Avoid brew warning about python deps while uninstalling

- host/hackrf-tools/src/hackrf_operacake.c
The hackrf_operacake long option --list was producing an error message "unknown argument '-v (null)' ".
> Fixed operation of switch --list

- firmware/common/operacake.c
- firmware/common/operacake.h
- firmware/hackrf_usb/hackrf_usb.c
- firmware/hackrf_usb/usb_api_operacake.c
- firmware/hackrf_usb/usb_api_operacake.h
- host/hackrf-tools/src/hackrf_operacake.c
- host/libhackrf/src/hackrf.c
- host/libhackrf/src/hackrf.h
Adds a GPIO test to `hackrf_operacake`.  You'll need to build and flash the firmware, then run `hackrf_operacake -o 24 -g`  (24 being the address of the EUT opera cake)
> HackRF Opera Cake - GPIO test mode

- .travis.yml
A fix for the Travis OS X build environment because we no longer need to work around oclint
> Remove oclint travis line because it's no longer installed by default

- .travis.yml
It's more likely to represent the platform that users use.
Sadly Travis-ci announced that they're ditching the container based build environment, so no more container builds.  All VMs from now on, so I took out the `sudo: false` restriction.
> Switch to xenial build platform (no more containers)

- firmware/common/w25q80bv.c
This line is meant to wait for the WEL bit to be set, to signify that
the WRITE_ENABLE command has finished.
The previous code didn't do any masking, so would hang if any other
status bits were set.
> Fix hang in w25q80bv_write_enable

- host/hackrf-tools/src/hackrf_transfer.c
When capturing on a Raspberry Pi 4, if you provide a filename (-r cap.iq), it stops at 2 GiB with a "Exiting... hackrf_is_streaming() result: streaming terminated (-1004)" message (32 bits problem?). If you use stdout (-r -) this limit disappears, but you get garbage at the end of the file coming from the signal handlers (that also print to stdout).
This is a simple fix to avoid that "problem" (not a big deal anyway).
> FIXED: remove garbage at the end when capturing to stdout ('-r -')

- host/hackrf-tools/src/hackrf_transfer.c
- host/libhackrf/src/hackrf.h
HackRF One supports arbitrary sample rates from 2 Msps to 20 Msps.  In
early development we had ideas about preferred sample rates that we no
longer consider valid.
> remove specific sample rate recommendations

- host/hackrf-tools/src/hackrf_transfer.c
hackrf_transfer failed to send file with size over 2G (in case 32bit system). Fix in hackrf_transfer.c  to change the position of the #define _FILE_OFFSET_BITS 64, must be defined before #include<sys/stat.h>
> fix _FILE_OFFSET_BITS 64 position in hackrf_transfer.c 

- host/libhackrf/src/hackrf.c
This fixes Issue #804 .
On at least freebsd-13 trying to cancel a transfer whilst the libusb thread
is not running results in the transfers not completing cancellation.
The next time they're attempted to be re-added the libusb code thinks
they're still active, and returns BUSY on the buffers.
This causes gqrx to error out when one makes DSP changes or stops/starts it.
You have to restart gqrx to fix it.
After digging into it a bit, the libusb code expects that you're actively
running the main loop in order to have some deferred actions run in the
context of said main loop thread.  This includes processing cancelled
transfers - the callbacks have to be run (if they exist) before the
buffers are properly cancelled and have their tracking metadata (a couple of
private pointers and state) …
> Fix libusb usage for at least freebsd around the worker thread and transfer cancellation

- firmware/hackrf_usb/usb_api_sweep.c
Previously, a USB vendor request could interrupt in the middle of
`set_freq` and make conflicting changes, leaving the HackRF in an
undefined state.
fixes #772
> Disable USB interrupts during sweep set_freq call

- host/hackrf-tools/src/hackrf_sweep.c
Thoroughly tested on Linux and macOS.
**hackrf_sweep: flush output earlier**
Gives listener access to complete data faster.
Otherwise the data might be delayed until the whole closing procedure is done.
**hackrf_sweep: speed up ending by removing unnecessary code**
hackrf_stop_rx() is handled in hackrf_close(), so there seems to be no need
to call it separately.  Furthermore, if hackrf_stop() is called separately,
it causes hackrf_close() to take more than half a second longer.
**hackrf_sweep: exit early from rx_callback if do_exit set**
Sometimes, if a small frequency interval is scanned, the callback is
triggered even though we already have the number of sweeps we want, and
sweep_count gets increased, showing the wrong "Total sweeps".
`time hackrf-tools/src/hackrf_sweep -f 100:320 -1 …
> Faster and cleaner exit from hackrf_sweep

- host/hackrf-tools/src/hackrf_sweep.c
If the binary mode flag -B is set, also set the process's stdout pipe mode to binary mode. If this is not done, the underlying c standard library functions on windows will assume text-mode and try to convert any 0x0A bytes to 0x0A 0x0D, mangling the binary output. This fixes QSpectrumAnalyzer being able to parse the binary output of the latest version hackrf_sweep on Windows.
See Issue #871
> Adding call to _setmode for Windows only to specify binary stdout output piping.

- host/hackrf-tools/src/hackrf_sweep.c
With this change,
`hackrf_sweep -f 100:120 -N 100`
reports
```
Total sweeps: 100 in 0.30062 seconds (332.64 sweeps/second)
```
instead of
```
Total sweeps: 100 in 0.30061 seconds (0.00 sweeps/second)
```
> hackrf_sweep: Calculate and show sweep rate for subsecond sweeps

- .github/workflows/build.yml
This sets up CI builds using Github Actions, in preparation for when travis-ci.org shuts down.
An example run: https://github.com/miek/hackrf/actions/runs/763674151
> Add Github Actions CI build

- firmware/common/usb_standard_request.c
When setting the USB configuration to zero we should return from the configured state to the address state according to the USB specification.
Fix #861
> Do not set USB device address to zero

- firmware/common/configure_file.cmake
- firmware/common/m0_bin.s.cmake
- firmware/hackrf-common.cmake
This uses `add_custom_command` to run a cmake script instead of using
`configure_file` directly, which allows for adding dependencies and
creates an ouput that can be depended on.
It also uses `add_custom_command` instead of `add_custom_target` to
create the M0 binary, since custom targets have no output file to depend
on.
Unfortunately, multiple targets cannot depend on the same generated file
or cmake tries to run the generation multiple times in parallel. So, the
.bin/.s generation is now duplicated for each target so they don't
conflict.
fixes #693
> Fix automatic rebuilding of M0 code

- host/hackrf-tools/src/hackrf_sweep.c
This removes support for longer dwell times at each frequency, something that I don't think has ever worked except perhaps in pre-release versions of hackrf_sweep.
fixes #865
fixes #951
> hackrf_sweep: simplify dwell time, bin width, and time stamps

- host/libhackrf/src/hackrf.h
> libhackrf: document hackrf_transfer struct

- .github/workflows/build.yml
Build in the libhackrf and hackrf-tools subdirectories in addition to the top host directory.
> add subdirectory builds to GitHub Actions

- docs/source/hackrf_one.rst
Enclosed `hackrf_debug` tool invocation into double back quotes (``) so that when it's rendered to HTML double hyphen is not converted to en dash.
> Fix double hyphen (--) rendered as en dash

- docs/source/software_support.rst
APRS tracker which uses the HTML Geolocation API to retrieve the
device's position and WebUSB to communicate with the HackRF. The source
code is available at https://github.com/rgerganov/aprs-sdr
> Add project mention for the APRS tracker

- firmware/hackrf_usb/hackrf_usb.c
- firmware/hackrf_usb/usb_api_sweep.c
- firmware/hackrf_usb/usb_api_sweep.h
- firmware/hackrf_usb/usb_api_transceiver.c
- firmware/hackrf_usb/usb_api_transceiver.h
- host/libhackrf/src/hackrf.c
Fixes bug #916.
Previously, there was a race which could lead to a transfer being left active after `cancel_transfers()` completed. This would then cause the next `prepare_transfers()` call to fail, because `libusb_submit_transfer()` would return an error due to the transfer already being in use.
The sequence of events that could cause this was:
1. Main thread calls `hackrf_stop_rx()`, which calls `cancel_transfers()`, which iterates through the 4 transfers in use and cancels them one by one with `libusb_cancel_transfer()`.
1. During this time, a transfer is completed. The transfer thread calls `hackrf_libusb_transfer_callback()`, which handles the data and then calls `libusb_submit_transfer()` to resubmit that transfer.
1. Now, `cancel_transfers()` and `hackrf_stop_rx()` are completed …
> Fixes for concurrency bugs in start/stop operations

- firmware/hackrf_usb/hackrf_usb.c
- firmware/hackrf_usb/usb_api_sweep.c
- firmware/hackrf_usb/usb_api_transceiver.c
- firmware/hackrf_usb/usb_api_transceiver.h
This is a defensive change to make the transceiver code easier to reason about, and to avoid the possibility of races such as that seen in #1042.
Previously, `set_transceiver_mode()` was called in the vendor request handler for the `SET_TRANSCEIVER_MODE` request, as well in the callback for a USB configuration change. Both these calls are made from the USB0 ISR, so could interrupt the `rx_mode()`, `tx_mode()` and `sweep_mode()` functions at any point. It was hard to tell if this was safe.
Instead, `set_transceiver_mode()` has been removed, and its work is split into three parts:
- `request_transceiver_mode()`, which is safe to call from ISR context. All this function does is update the requested mode and increment a sequence number. This builds on work already done in PR #1029, but the …
> Move transceiver mode changes out of USB ISR.

- host/libhackrf/src/hackrf.c
transfer_threadproc has a timeout of half a second, so
when kill_transfer_thread tries to pthread_join, it often
has to wait until the timeout kicks in.
With this fix, we ensure that a final request is made after
request_exit has been called, so that transfer_threadproc can exit its
loop in a fast and clean manner.
> Ensure fast exit

- firmware/common/usb.c
- firmware/common/usb.h
- firmware/common/usb_standard_request.c
- firmware/common/usb_type.h
From USB 2.0, section 9.4.5:
> For endpoints using data toggle, regardless of whether an endpoint has the Halt feature set, a ClearFeature(ENDPOINT_HALT) request always results in the data toggle being reinitialized to DATA0.
Hopefuly fixes #1052, but not tested yet.
> Implement USB CLEAR_FEATURE request for ENDPOINT_HALT

- firmware/hackrf_usb/usb_api_board_info.c
- firmware/hackrf_usb/usb_api_cpld.c
- firmware/hackrf_usb/usb_api_operacake.c
- firmware/hackrf_usb/usb_api_spiflash.c
After a passing comment from @miek some time ago, I had it on my todo list to check all the USB vendor request handlers for this problem.
Four of them were scheduling responses from locals on the stack, which could be overwritten by the time the host polls the device for the response.
This PR fixes that by putting their data in the endpoint buffer instead, or in another persistent location if that buffer is too small.
> Fix USB requests that were responding with data from the stack.

- host/libhackrf/src/hackrf.c
This PR ensures correct behaviour during shutdown, and reviews and simplifies usage of the `streaming` and `do_exit` flags. The changes are as follows:
- The transfer callback no longer calls `request_exit()` to end the transfer thread if an error occurs. It was no longer safe to do this after the changes in #1029, because we need the transfer thread to keep running, to handle cancellations and signal when these are complete. Instead, if it sees an error, the callback just records the transfer as finished, and clears the `streaming` flag. This fixes #1068.
- The transfer callback will no longer call the user RX callback, or submit further transfers, once the `streaming` flag is cleared. This ensures that:
- Once the RX callback returns nonzero to indicate completion, it is not called …
> Overhaul handling of transfer errors and use of streaming flag.

- host/libhackrf/src/hackrf.c
This is stacked on #1069 to avoid conflicts, so until that's merged, start reviewing from commit [`958c742`](https://github.com/greatscottgadgets/hackrf/pull/1070/commits/958c7421890c62436e198547473ccfcd3d838c46).
The changes in this PR are:
- Remove the 10ms delays that were added to `hackrf_stop_rx_cmd` and `hackrf_stop_tx_cmd` in PR #805.
- These delays were a workaround to ensure that their calling functions did not return until transfer cancellations had completed. That problem is now fixed properly in #1029, so the delays are no longer necessary.
- Merge `hackrf_stop_rx_cmd` and `hackrf_stop_tx_cmd`, since they do the same thing: set transceiver mode to OFF.
- Remove the duplicate use of that command in `hackrf_close`.
> Remove unnecessary delays on stop, and duplicated stop commands on close.

- host/libhackrf/src/hackrf.c
This is a followup cleanup to #1029.
This PR simplifies the logic for tracking finished transfers, by removing the per-transfer `transfer_finished` flags and the overall `all_finished` flag, and replacing them with a count of `active_transfers`. 
From a concurrency point of view everything works as before, except that the pthread condition variable is now associated with the assertion `active_transfers == 0` rather than `all_finished`. The associated lock must therefore be held to decrement that count to zero, and the condition is signalled when this happens.
I proposed this simplification in [this comment](https://github.com/greatscottgadgets/hackrf/pull/1029#issuecomment-1019592611) on PR #1029, but left it out of that PR in order to get a working fix merged ASAP.
> Simplify logic for tracking finished transfers

- firmware/hackrf_usb/usb_api_transceiver.c
As reported by @schneider42, the RX loop could get stuck if the rad1o UI update blocked it for long enough.
We can fix this, and simplify the code, by tracking the count of bytes scheduled for USB transfer, rather than the buffer phase.
The same thing can be done for the TX loop.
> Simplify RX and TX loops

- host/hackrf-tools/src/hackrf_transfer.c
`stream_amplitude` was only being updated in `rx_callback()` and not in `tx_callback()`.
> Fix #902 - Report transmit amplitude

- docs/source/external_clock_interface.rst
- firmware/hackrf_usb/hackrf_usb.c
- firmware/hackrf_usb/usb_api_register.c
- firmware/hackrf_usb/usb_api_register.h
- host/hackrf-tools/src/hackrf_clock.c
- host/libhackrf/src/hackrf.c
- host/libhackrf/src/hackrf.h
Add a new `hackrf_clock` option (`-i` or `--clkin`) which reports the CLKIN status, and doesn't require remembering cryptic Si5351 register values.
> Add a simpler way to check CLKIN status.

- host/hackrf-tools/src/hackrf_transfer.c
Rather than using `sleep` for 1s at a time, set up an interval timer that will fire once per second, and wait in the main loop for either this or some other event.
On POSIX, the timing is set up with `setitimer`, which generates a `SIGALRM` signal each time the timer fires. The main loop runs `pause` to wait for any signal.
On Windows, the timing is set up using `CreateWaitableTimer`, which provides an event handle that is set each time the timer fires. The main loop runs `WaitForMultipleObjects` to wait on this and an interrupt event.
The TX and RX callbacks can now stop the main loop immediately when they stop streaming. This fixes #1019.
> Overhaul timing in hackrf_transfer

- host/hackrf-tools/src/hackrf_transfer.c
This PR adds some additional checks to arguments passed to `hackrf_transfer`:
- The `-s` option now checks that the sample rate is in the supported range of 2 to 20 MHz.
- The `-f` option now checks that the RF frequency is in the supported range of 1 to 6000 MHz.
- The new `-F` argument allows setting values outside the supported ranges above. The maximum RF frequency is still limited to 7250 MHz with this option, but no other limits are applied.
Closes #1041.
> Additional argument validation for hackrf_transfer

- host/hackrf-tools/src/hackrf_transfer.c
This PR fixes repeated transmission of short sample files using `hackrf_transfer`:
- The first three commits simplify the TX and RX callbacks, by using early returns rather than deeply indented conditional blocks. There should be no functional change from these commits.
- The main change is in https://github.com/greatscottgadgets/hackrf/pull/1132/commits/0c35cff05b061afae12b804fffb37e51bfbc9835, which adds a loop which repeatedly rewinds the file until the transfer buffer is filled.
- Finally the message `Input file end reached. Rewind to beginning` is removed, because with short input files it can be printed an extremely large number of times.
Closes #720.
> Support repeating short files in `hackrf_transfer`

- firmware/common/operacake.c
- firmware/common/operacake.h
- firmware/hackrf_usb/usb_api_operacake.c
> operacake: disable the usage of time mode when a portapack is installed

- host/hackrf-tools/src/hackrf_transfer.c
- host/libhackrf/src/hackrf.c
- host/libhackrf/src/hackrf.h
This is a rewrite of the amplitude measurement and reporting that greatly improves accuracy and reliability.
One remaining potential source of unreliability is the fact that `byte_count` and `stream_power` are not written, read, or reset atomically as a pair, but making those operations adjacent so that they happen at approximately the same time eliminated all symptoms of concurrency problems in tests on my system. I think that locking (or a lock-free ring buffer for stats) would be required to guarantee 100% reliability, but I don't feel that it is worth that complication. The worst thing that could happen is that the reported stats are a bit off.
Additionally this updates the `-c` option to accept CW amplitude configuration up to 128. Previously it was limited to 127 (maximum …
> Measure digital signal power, not amplitude in hackrf_transfer

- host/hackrf-tools/src/hackrf_transfer.c
- host/libhackrf/src/hackrf.c
- host/libhackrf/src/hackrf.h
This PR adds two new functions to libhackrf:
- `hackf_enable_tx_flush(device, enable)`: When called before `hackrf_start_tx`, this will make libhackrf submit an additional USB transfer containing 32KB of zeros after the last samples from the TX callback. This is the size of the device's TX buffer.
- `hackrf_await_tx_flush(device)`: When called after `hackrf_enable_tx_flush` this will wait until that additional USB transfer completes. Once that happens, it is guaranteed that all user samples have been transmitted, so it is safe to call `hackrf_stop_tx` without truncating the transmission.
These calls are then added to `hackrf_transfer`.
> Support flushing the device TX buffer before ending transmission

- firmware/common/hackrf_core.h
- firmware/common/platform_detect.c
- firmware/common/platform_detect.h
- firmware/hackrf-common.cmake
- firmware/hackrf_usb/hackrf_usb.c
- firmware/hackrf_usb/usb_api_board_info.c
- firmware/hackrf_usb/usb_api_board_info.h
- host/hackrf-tools/src/hackrf_info.c
- host/hackrf-tools/src/hackrf_spiflash.c
- host/libhackrf/src/hackrf.c
- host/libhackrf/src/hackrf.h
Firmware now detects the hardware it is running on at startup and refuses to run if it is compiled for the wrong platform. The board ID returned by firmware to the host is now derived from run-time detection rather than a compile-time value. A separate method to retrieve compile-time supported platform is added.
On HackRF One, pin straps are checked to determine hardware revision. This is informational to aid troubleshooting and does not affect any function.
> Detect hardware platform at run-time.

- host/hackrf-tools/src/hackrf_transfer.c
[Decibels relative to full scale (dBFS)](https://en.wikipedia.org/wiki/DBFS) is defined in AES Standard AES17-1998, IEC 61606, and ITU-T Recs. P.381 and P.382, such that the RMS value of a full-scale sine wave is designated 0 dBFS.
The largest possible zero-centred sine wave on HackRF has the range -127 to 127. This PR corrects the calculation of dBFS in `hackrf_transfer` such that a sine wave of that amplitude should read 0 dBFS.
The `hackrf_transfer -c` option previously applied a constant amplitude to both I and Q, with the maximum of 128 creating a vector magnitude of ~181 and a level of +3 dBFS, previously reported as 0 dBFS. Instead, this PR applies the requested amplitude to the I channel only, setting Q to zero.
The maximum amplitude is limited to 127, such that the maximum …
> Standardise dBFS level

- host/hackrf-tools/src/hackrf_transfer.c
- host/libhackrf/src/hackrf.c
This PR fixes handling of the final samples in a transmission sent with `hackrf_transfer`.
Previously, `hackrf_transfer` would drop the last < 256KiB from of any source of samples, when it could not populate a full transfer buffer.
The changes are:
- Some general cleanup in the `hackrf_transfer` TX callback, to clarify things and avoid duplicated code.
- Make libhackrf honour the `valid_length` set by a TX callback and put this in the libusb transfer length.
- In the `hackrf_transfer` TX callback, set `valid_length` to the bytes put in the buffer when filling a final short transfer.
- After filling the final transfer, return 0 from the callback to submit it, postponing the -1 return until the next call.
> Fix handling of the final <256KiB of data transmitted with `hackrf_transfer`

- host/hackrf-tools/src/hackrf_transfer.c
- host/libhackrf/src/hackrf.h
Mostly this is just some simplification and clean-up. Fixes termination of `hackrf_transfer` when called from a script. Also fixes RX stats with small `-n`.
> clean-up and small bug fixes

- host/libhackrf/src/hackrf.h
This is intended to solve the concern raised on #1155, making https://github.com/pothosware/SoapyHackRF/pull/36 unnecessary.
> libhackrf: #define outdated board IDs

- host/libhackrf/src/hackrf.c
Where our callback is called with a status other than `LIBUSB_TRANSFER_COMPLETED`, something abnormal has happened and we no longer want to either submit further transfers or await a flush. So clear both the `streaming` and `flush` flags, and proceed to transfer_finished.
Do the same if `libusb_submit_transfer` fails when called from our callback to submit the flush transfer.
This fixes #1163.
> Fix hang in TX when a libusb error occurs.

- firmware/common/rf_path.c
Previously `rf_path_pin_setup` would set up the GPIOs with:
`switchctrl_set(rf_path, SWITCHCTRL_AMP_BYPASS | SWITCHCTRL_MIX_BYPASS)`
However, this misses out `SWITCHCTRL_NO_TX_AMP_PWR` and `SWITCHCTRL_NO_RX_AMP_PWR` which are needed to keep the amps off. The correct setting to use is defined as `SWITCHCTRL_SAFE`. The call was also made after setting the GPIOs to output mode, so there could be a brief glitch.
The `SWITCHCTRL_SAFE` value was being assigned to the global `switchctrl` setting but this was only used once, in `rf_path_init`, which does apply that state shortly after `rf_path_pin_setup`. However, all other functions use `rf_path->switchctrl`, not the global `switchctrl`, which was never being initialised at all.
This PR corrects these issues, which fixes #1169.
> Fix initial state of RF path GPIOs.

- host/hackrf-tools/src/hackrf_transfer.c
- host/libhackrf/src/hackrf.c
- host/libhackrf/src/hackrf.h
This fixes #1164, but currently causes some erroneous output to be printed in `hackrf_transfer` e.g:
```
$ hackrf_transfer -c 0 -n 100000
call hackrf_set_sample_rate(10000000 Hz/10.000 MHz)
call hackrf_set_hw_sync_mode(0)
call hackrf_set_freq(900000000 Hz/900.000 MHz)
samples_to_xfer 100000/0Mio
Stop with Ctrl-C
0.0 MiB / 0.011 sec =  0.0 MiB/second, average power -nan dBfs
Couldn't transfer any bytes for one second.
```
> Provide a callback for TX flush, rather than a wait function.

- firmware/common/usb_request.c
On macOS 12.6 running libusb 1.0.26, the host was seen to sometimes make an incomplete `ClearFeature(ENDPOINT_HALT)` request when `ClearPipeStallBothEnds` was called from `libusb_cancel_transfer`.
The host would send the SETUP packet, and the firmware would call `usb_transfer_schedule_ack` to acknowledge the upcoming IN token. However, the host would then not send the IN token, proceeding directly to the next SETUP:
Since an empty transfer was queued to schedule the ACK, the firmware would leak one transfer from the `free_transfers` list.
After a few iterations of this, the firmware would run out of free transfers and the next request would hang waiting for one.
Fix this by flushing the transfer queues for the control endpoint when a new SETUP is received, since that token implicitly …
> Flush queues on control endpoint when a new SETUP is received.

- firmware/hackrf-common.cmake
- host/cmake/set_release.cmake
Starting with this release we will no longer use "unknown" as the default software version string used in cases where the version cannot be determined from context. Instead we commit the release version string to git so that any software built from the tagged commit will have the appropriate release version string. After the release we will commit a post-release version string as the new default.
We will continue to use the commit hash as version string when the software is built inside a git repository.
> set version to 2022.09.1

- firmware/hackrf_usb/usb_api_transceiver.c
This PR reduces the size of firmware-side USB transfers from 16KB to 8KB: a quarter of the available buffer, rather than half.
This provides greatly improved throughput in practice:
* With 16KB transfers, Windows and macOS would both typically fail to maintain sufficient USB throughput above 16-17Msps sample rates, with only Linux sustaining 20Msps. With 8KB transfers, all three operating systems now sustain 20Msps. 
* With 16KB transfers, Linux would sustain 20Msps TX but with occasional brief underruns. With 8KB transfers, there are none. Buffer stats printed from `hackrf_transfer -B` clearly show a higher and more consistent level of data in the buffer.
The smaller transfer size helps because it reduces sensitivity to latency. Previously, the device had to NAK the IN/OUT tokens from …
> Reduce firmware USB transfer size from 16KB to 8KB

- firmware/hackrf_usb/hackrf_usb.c
The rad1o was not starting the M0 when powered up by inserting a USB cable. Interestingly the M0 does start when toggling the power switch.
Resetting the M0 before starting it in `main()` solves this issue.
> m0: reset M0 before starting it

- firmware/hackrf_usb/sgpio_m0.s
The definition of `prev` is `r1` at line 360 in macro `handle_shortfall`, but is later changed to `r0` in `checked_rollback` at line 569.  This causes a warning message:
`sgpio_m0.s:569: Warning: ignoring redefinition of register alias 'prev'`
Doing a disassembly shows that the assembler indeed ignores the redefinition and uses `r1` in `checked_rollback`.
This pull request simply changes the definition in `checked_rollback` to match what macro `handle_shortfall` is using, and thus eliminates the warning without actually changing the binary code that is generated.
> Make definition of "prev" consistent

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/documentation-request.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/question.yml
- .github/ISSUE_TEMPLATE/technical-support.yml
This removes the pre-populated titles from the issue form templates. I think in practice they end up being confusing, and users often either overwrite them or leave the title empty. Since the template adds labels to the issues anyway, I think we can remove the title tags.
> Remove default titles from issue forms

- .github/workflows/build.yml
This PR adds a Windows MSVC build of libhackrf and the host tools to our existing Github Actions workflow. The aim is to replace the current Appveyor builds, which use outdated dependencies and require a separate CI platform.
The build uses the current GitHub `windows-latest` runner. The dependencies (libusb, pthreads and fftw) are first installed via [vcpkg](https://github.com/microsoft/vcpkg/). The latest versions currently available through the installed vcpkg will be used.
Builds are then configured, passing all the necessary header and library paths to CMake's configure step, which generates MSBuild project files. Ideally, explicitly specifying the paths should be eliminated in future by having our CMake scripts integrate better with vcpkg, but the current approach works for now …
> Add Windows build of libhackrf and host tools to Github Actions

- firmware/common/firmware_info.c
- firmware/common/firmware_info.h
- firmware/common/platform_detect.c
- firmware/common/usb_type.h
- firmware/hackrf-common.cmake
- firmware/hackrf_usb/usb_api_board_info.c
- host/hackrf-tools/src/hackrf_spiflash.c
- host/libhackrf/src/hackrf.c
- host/libhackrf/src/hackrf.h
This adds a structure at a fixed location within the firmware image, to provide information about the firmware image.
In particular, it has a field to specify which hardware platforms the firmware image supports that `hackrf_spiflash` can use to warn about flashing incompatible firmware. This replaces the old method of searching the USB string descriptors and allows for a firmware image to support multiple platforms.
I've marked this as a draft for now as it depends on https://github.com/mossmann/libopencm3/pull/31 to define a new section for the struct. Once that's merged in, I'll add a submodule-update commit & rebase.
> Add firmware info structure

- firmware/common/hackrf_core.c
- firmware/hackrf_usb/hackrf_usb.c
fixes #1292; requires two calls to clkin_detect_init which should also be fixed
> wrap clkin init in r9 board check

- host/libhackrf/src/hackrf.c
hackrf_transfer uses pause() and SIGALRM to print statistics and POSIX doesn't specify which thread must recieve the signal, block all signals in transfer_threadproc(), so we don't interrupt their reception by hackrf_transfer or any other app which uses the library (#1323)
> mask all signals in libhackrf transfer_threadproc

- .github/workflows/build.yml
This fixes the macOS firmware builds.
> Switch to gcc-arm-embedded package for macOS CI build

- host/hackrf-tools/src/hackrf_sweep.c
Hi,
I think I found a problem on hackrf_sweep, regarding the handling of the timestamp of the detections.
Using the maximum frequency range, 0:7250, you can see that within the same sweep the timestamp of the detections changes.
This change causes the unexpected spectrogram plotted by plotsweep.
how to reproduce the issue:
```
bash-3.2$ ./hackrf-tools/src/hackrf_sweep -f 0:7250 -w 1000000 -N 50 -r test1.csv
call hackrf_sample_rate_set(20.000 MHz)
call hackrf_baseband_filter_bandwidth_set(15.000 MHz)
Sweeping from 0 MHz to 7260 MHz
Stop with Ctrl-C
1 total sweeps completed, 0.98 sweeps/second
2 total sweeps completed, 0.98 sweeps/second
3 total sweeps completed, 0.98 sweeps/second
4 total sweeps completed, 0.98 sweeps/second
5 total sweeps completed, 0.98 sweeps/second
6 total sweeps …
```
> hackrf_sweep: normalized timestamp

- firmware/hackrf_usb/usb_api_transceiver.c
This reverts PR #1203, which introduced bug #1363.
The problem is as summarised [here](https://github.com/greatscottgadgets/hackrf/pull/1203#issuecomment-1848791434):
> The 32KB sample buffer straddles a block boundary such that each 16KB half-buffer is in a separate SRAM block which has its own independent AHB bus connection. With 16KB transfers, the M0 and the USB peripheral were always accessing different blocks. This change to 8KB transfers allowed the USB peripheral to start reading from the first 8KB of a 16KB half-buffer while the M0 core was still writing to the second 8KB. The contention caused by having two bus masters accessing the same SRAM block added intermittent latency, causing the M0 to sometimes miss its SGPIO timing deadlines.
Reverting this PR will eliminate the …
> Revert "Reduce firmware USB transfer size from 16KB to 8KB."

- .github/ISSUE_TEMPLATE/technical-support.yml
The technical support issue template was pointing at a specific "troubleshooting" page that no longer exists in the documentation.
Pointed it to the top level of the documentation instead.
> Update documentation link in issue template.

- Jenkinsfile
- ci-scripts/test-firmware-program.sh
- ci-scripts/test-sgpio-debug.py
This is expected to fail on latest and pass before fefa4f0e4592b8fb235d38e60fb5daea4974ff95
> sgpio debug ci test

- host/CMakeLists.txt
- host/hackrf-tools/CMakeLists.txt
- host/libhackrf/CMakeLists.txt
To remove the CMAKE build [deprecation warning](https://github.com/greatscottgadgets/hackrf/issues/831), update the minimum required version.
> Update CMAKE minimum version to 2.8.12

- .github/workflows/build.yml
- .github/workflows/clang-format-check.yml
- .gitignore
- host/hackrf-tools/src/CMakeLists.txt
- host/libhackrf/src/CMakeLists.txt
This PR adds a new windows build package artifact to each build, and also addresses a number of windows-related build issues.
The primary change with this pull request is the addition of a new artifact on build called `hackrf-tools-windows.zip`. This artifact contains the combination of the windows libhackrf build and hackrf-tools build together. The intent of this artifact is to provide a convenient way for Windows users who prefer to download pre-built Windows binaries to do so from an official source. This is the first step in a longer-term vision to be able to auto-package the HackRF One libraries and tools around a more comprehensive installer.
Specific changes in this pull request are:
* Add artifact publish step for Windows libraries and host tools.
* Replace runner.workspace with …
> Auto-package windows binaries on build (and fix a few bugs and warnings)

- docs/source/list_of_hardware_revisions.rst
The previous markdown was not valid and yielded the following warning:
```sh
⬛make html
Running Sphinx v5.3.0
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 34 source files that are out of date
updating environment: [new config] 34 added, 0 changed, 0 removed
reading sources... [100%] virtual_machines
hackrf/docs/source/list_of_hardware_revisions.rst:36: WARNING: Title underline too short.
HackRF One r10
~~~~~~~~~~~~~
hackrf/docs/source/list_of_hardware_revisions.rst:36: WARNING: Title underline too short.
HackRF One r10
~~~~~~~~~~~~~
looking for now-outdated files... none …
```
> doc: markdown heading

- docs/source/firmware_development_setup.rst
- docs/source/installing_hackrf_software.rst
- docs/source/updating_firmware.rst
In the installing_hackrf_software docs, under "Installing From Source", the source url still points to `git clone https://github.com/mossmann/hackrf.git` instead of `https://github.com/greatscottgadgets/hackrf.git`
Unlike the other browser links, the git url is not automatically redirected, so cloning will fail:
```
jg@buildbot:~/hackrf$ git clone https://github.com/mossman/hackrf.git
Cloning into 'hackrf'...
remote: Repository not found.
fatal: repository 'https://github.com/mossman/hackrf.git/' not found
```
While creating this patch, I also found a few more of those older urls and updated them too. One last unfixed url remains at https://hackrf.readthedocs.io/en/latest/LPC43XX_Debugging.html#lpc-link, however I could not find the intended destination so I have left it as-is.
> docs: update github.com/mossmann urls

- host/libhackrf/src/hackrf.h
> Correct prototype of flush callback in example code.

- Dockerfile
- Jenkinsfile
- ci-scripts/configure-hubs.sh
- ci-scripts/test-firmware-program.sh
- ci-scripts/test-host.sh
- ci-scripts/test-transfer.py
- Moves usb hub port->device mapping responsibility to the Jenkins test server.
- Builds docker image from `master:latest` to prevent malicious changes to the Dockerfile from being run on PR.
Note: [0212bf6](https://github.com/greatscottgadgets/hackrf/pull/1466/commits/0212bf625a199d0b0bb713bc408f884426f68908) is expected to [fail the Jenkins build](https://jenkins.greatscottgadgets.com/job/greatscottgadgets-organization/job/hackrf/job/PR-1466/4/console) until it's [replayed with `$GIT_URL` pointing to my fork](https://jenkins.greatscottgadgets.com/job/greatscottgadgets-organization/job/hackrf/job/PR-1466/5/console) since `gsg:master:latest` doesn't yet have the updated Dockerfile required for running the new hub commands.
> ci: usb hub ppps handling overhaul

- firmware/common/portapack.c
This pull request adds the AGM Microelectronics AG256SL100 to the portapack detection routine.
Almost all new portapacks are now made with the AGM CPLD. Without the ability to detect them in the stock hackrf firmware, users will just see a black screen and might think there is a defect as long as they didn't replace the firmware. So this should reduce user confusion and might even reduce support requests on both sides.
In the portapack firmware this fix is already injected into the "hackrf mode", but our compilation is somewhat messy now (can't just use your CMakeLists.txt).
> Add AGM CPLD to portapack detection routine

- firmware/hackrf_usb/sgpio_m0.s
- host/hackrf-tools/src/hackrf_debug.c
- host/libhackrf/src/hackrf.h
Checks whether the M0 core missed its deadline: i.e. if the next SGPIO interrupt already occurred by the time it finished processing the last one.
If so, the M0 returns to the idle mode with an error code in the M0 state. This should cause the host tools to time out, at which point the error can be checked with `hackrf_debug -S`.
> SGPIO deadline check

- firmware/common/usb.c
- firmware/common/usb.h
- firmware/common/usb_queue.c
That PR is fixing all the following warnings:
```
In file included from ~/portapack-mayhem/hackrf/firmware/common/usb.c:26:
~/portapack-mayhem/hackrf/firmware/common/usb.h:32:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
32 | void usb_peripheral_reset();
| ^~~~
~/portapack-mayhem/hackrf/firmware/common/usb.h:33:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
33 | void usb_phy_enable();
| ^~~~
In file included from ~/portapack-mayhem/hackrf/firmware/common/usb.c:32:
~/portapack-mayhem/hackrf/firmware/libopencm3/include/libopencm3/lpc43xx/m4/nvic.h:45: warning: "NVIC_SGPIO_IRQ" redefined
45 | #define NVIC_SGPIO_IRQ 31
| 
In file included from ~/portapack-mayhem/hackrf/firmware/libopencm3/include/libopencm3/dispatch/nvic.h:30,
from …
```
> fix compilation warnings

- firmware/common/locking.h
- firmware/common/usb.c
- firmware/common/usb_queue.c
Required to allow the USB queue code to be built for the M0.
> Add a shim header to support locking without ldrex/strex

- firmware/common/locking.h
Following the comment here: https://github.com/greatscottgadgets/hackrf/pull/1517#issuecomment-2549482791
We are getting undefined reference to enable/disable irq calls.
I'm providing a fix for build on m0, based on the definition that can be found in chibios.
> define replacement for enable and disable irq for m0

- host/libhackrf/src/hackrf.c
At the request of @martinling, here's a draft PR that implements RAW_IO on Windows, using libusb/libusb#1512. The change checks if RAW_IO is available, and if it is, it turns it on for the `RX_ENDPOINT_ADDRESS`. I've made it silently ignore the result of `libusb_endpoint_set_raw_io`, since in the unlikely event of the call not working, I'd think we should continue on anyway.
This change fixes sample drops on problematic Windows machines. I've marked the PR a draft because this change will require `#if LIBUSB_API_VERSION >= 0x0100010B ... #endif` to prevent issues when building with older versions of LibUSB. The problem is:
- The change isn't actually merged into LibUSB yet (hopefully it is soon!)
- `LIBUSB_API_VERSION` has not been bumped yet. It's still sitting at 0x0100010A, so there's …
> Implement RAW_IO with WinUSB

- host/hackrf-tools/src/hackrf_clock.c
- host/hackrf-tools/src/hackrf_debug.c
- host/hackrf-tools/src/hackrf_operacake.c
- host/hackrf-tools/src/hackrf_spiflash.c
- host/hackrf-tools/src/hackrf_sweep.c
- host/hackrf-tools/src/hackrf_transfer.c
- host/libhackrf/src/hackrf.c
It's been 25 years since C99... I think we can depend on `stdbool.h` now.
Fixes #1588.
> Use stdbool.h rather than our own bool definition

- host/cmake/cmake_uninstall.cmake.in
Uses the current version of the advice from:
https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake
rather than the previous  version from a long-dead URL for the same FAQ.
> Update CMake code for producing 'make uninstall' target

- .github/workflows/build.yml
- host/cmake/modules/FindLIBUSB.cmake
This cuts down the number of settings that need to be passed.
> CMake: support use of pkgconf to find libraries on Windows
